# Generated by Django 4.2 on 2025-09-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='teams',
        ),
    ]
