# Generated by Django 4.2 on 2025-09-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_remove_person_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='teams', to='scores.person'),
        ),
    ]
