# Generated by Django 4.2 on 2025-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_event_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='competitions',
            field=models.ManyToManyField(null=True, to='scores.competition'),
        ),
        migrations.AlterField(
            model_name='team',
            name='people',
            field=models.ManyToManyField(null=True, to='scores.person'),
        ),
    ]
