# Generated by Django 4.2 on 2025-05-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_team_competitions_alter_team_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='competitions',
            field=models.ManyToManyField(blank=True, to='scores.competition'),
        ),
        migrations.AlterField(
            model_name='team',
            name='people',
            field=models.ManyToManyField(blank=True, to='scores.person'),
        ),
    ]
