# Generated by Django 4.2 on 2025-09-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_team_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='competitions',
        ),
    ]
