# Generated by Django 4.2 on 2025-05-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_alter_team_competitions_alter_team_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='InMatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('card', 'Card'), ('entry', 'Entry'), ('exit', 'Exit'), ('goal', 'Goal')], max_length=10)),
                ('minute', models.IntegerField()),
                ('detail', models.CharField(max_length=250)),
                ('color', models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('red', 'Red')], help_text="Only applicable if event_type is 'card'.", max_length=10, null=True)),
                ('goal_type', models.CharField(blank=True, choices=[('penalty', 'Penalty'), ('freekick', 'Freekick'), ('open_play', 'Open Play'), ('own_goal', 'Own Goal')], default='open_play', help_text="Only applicable if event_type is 'goal'.", max_length=10, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scores.match')),
                ('other_player', models.ForeignKey(blank=True, help_text="Only applicable if event_type is 'entry' or 'exit'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scores.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scores.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='other_player',
        ),
        migrations.RemoveField(
            model_name='event',
            name='match',
        ),
        migrations.RemoveField(
            model_name='event',
            name='person',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='other_player',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='event_ptr',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Exit',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
