# Generated by Django 4.2 on 2025-09-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_remove_team_competitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='scores.team'),
        ),
    ]
