# Generated by Django 4.2 on 2025-05-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_inmatchevent_remove_entry_event_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='scope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, to='scores.team'),
        ),
        migrations.AlterField(
            model_name='inmatchevent',
            name='detail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inmatchevent',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scores.match'),
        ),
        migrations.AlterField(
            model_name='inmatchevent',
            name='minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_home', to='scores.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='first_team_goals_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_away', to='scores.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_team_goals_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, choices=[('to_be_scheduled', 'To Be Scheduled'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('postponed', 'Postponed')], default='to_be_scheduled', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='teams',
            field=models.ManyToManyField(blank=True, to='scores.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
