# Generated by Django 4.2 on 2025-05-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_alter_competition_scope_alter_competition_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmatchevent',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='scores.match'),
        ),
    ]
