# Generated by Django 4.2 on 2025-05-27 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_alter_inmatchevent_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inmatchevent',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('penalty', 'Penalty'), ('freekick', 'Freekick'), ('open_play', 'Open Play'), ('own_goal', 'Own Goal')], help_text="Only applicable if event_type is 'goal'.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inmatchevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
