# Generated by Django 4.2 on 2025-06-07 07:59

from django.db import migrations, models
import django.db.models.deletion
import scores.models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_alter_competition_id_alter_inmatchevent_goal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(blank=True, default=scores.models.get_default_team_id, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_home', to='scores.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(blank=True, default=scores.models.get_default_team_id, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_away', to='scores.team'),
        ),
    ]
