# Generated by Django 4.2 on 2025-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_alter_match_first_team_alter_match_second_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmatchevent',
            name='event_type',
            field=models.CharField(choices=[('card', 'Card'), ('substitution', 'Substitution'), ('goal', 'Goal')], max_length=20),
        ),
    ]
