# Generated by Django 4.2 on 2025-06-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_alter_inmatchevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.competition'),
        ),
    ]
