name: Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker compose -f docker-compose.yaml up -d --build

    - name: Wait for DB to be ready
      run: docker compose exec django ./wait-for-it.sh postgres-db:5432

    - name: Run tests
      run: docker compose run --rm django pytest --junitxml=reports/test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/test-results.xml

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Pytest Results
        path: reports/test-results.xml
        reporter: jest-junit
        